name: "Send To IFTTT"
author: "hugoalh"
description: "Send data to IFTTT applet via webhook, support variables."
inputs:
  webhook_eventname:
    description: "[String] Webhook event name."
    required: true
  webhook_key:
    description: "[Secret String] Webhook key."
    required: true
  value1:
    description: "[String] Default IFTTT ingredient namespace."
    required: false
  value2:
    description: "[String] Default IFTTT ingredient namespace."
    required: false
  value3:
    description: "[String] Default IFTTT ingredient namespace."
    required: false
  variable_list_0_name:
    description: "[String] Namespace for this variable list."
    required: false
  variable_list_0_data:
    description: "[Stringified JSON] Variable list that will use in the data."
    required: false
  variable_list_1_name:
    description: "[String] Namespace for this variable list."
    required: false
  variable_list_1_data:
    description: "[Stringified JSON] Variable list that will use in the data."
    required: false
  variable_list_2_name:
    description: "[String] Namespace for this variable list."
    required: false
  variable_list_2_data:
    description: "[Stringified JSON] Variable list that will use in the data."
    required: false
  variable_list_3_name:
    description: "[String] Namespace for this variable list."
    required: false
  variable_list_3_data:
    description: "[Stringified JSON] Variable list that will use in the data."
    required: false
  variable_prefix:
    description: "[String] Variable prefix."
    required: false
    default: "%"
  variable_suffix:
    description: "[String] Variable suffix."
    required: false
    default: "%"
  variable_join:
    description: "[String] Variable join if having multiple variable lists, and/or variable list has depth."
    required: false
    default: "_"
runs:
  using: "node12"
  pre: "setup.js"
  main: "main.js"
branding:
  icon: "send"
  color: "blue"
